# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='lan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.IntegerField(),
        ),
    ]
